nexusProxy:
  env:
    nexusHttpHost: artifactory.dev.webtree.org

statefulset:
  enabled: true

ingress:
  enabled: true
  tls:
    enabled: false

persistence:
  storageSize: 5Gi

nexus:
  nodeSelector:
    wt-type: backend